# Any copyright is dedicated to the Public Domain.
# http://creativecommons.org/publicdomain/zero/1.0/

language: rust

rust:
    - nightly
    - beta
    - stable

script:
    - |
        cargo build &&
        cargo test &&
        cargo bench &&
        cargo run &&
        cargo doc
